### ISSUE TITLE
Long sidebar content is unreachable

### ISSUE THREAD

**Issue by EvanHerman** [godaddy-wordpress/primer-child-escapade#38]
When the content of the theme sidebar reaches beyond the height of the screen the content becomes unreachable as it is outside the view of the screen.

This was reportedly fixed in d6c68026200bfa3ac3bbc6904ce1a26003e8881e , but I am still seeing the issue.

See #22

**Example**
<img src="https://cldup.com/EiZLV-9SoQ.png" width="60%" />

There are a few menu items that are being cut off. Scrolling down the page doesn't reveal them as the sidebar remains static.

As the user scrolls down the page the sidebar should also scroll until it hits the bottom.

**Comment by fjarrett** [comment]
@EvanHerman Are we saying the sidebar should behave the same way Twenty Fifteen's does?

http://blog.wpnux.godaddy.com/hello-world/?theme=twentyfifteen

**Comment by jonathanbardo** [comment]
@fjarrett We can either go the twenty fifteen way or add a scroll on that menu I think.

**Comment by EvanHerman** [comment]
@fjarrett Correct. I had envisioned the way Twenty Fifteen does it. I think that is a more elegant solution as opposed to having two containers that scroll independently.

**Comment by jonathanbardo** [comment]
@EvanHerman But again having the whole website scroll when you only want to see more menu items is kind of weird.

**Comment by EvanHerman** [comment]
@jonathanbardo Oh right, we had this discussion back on Monday. Having the scroll bar with an offset so it's hidden, forgot we came to that conclusion.

**Comment by JawzoD3TH** [comment]
I'm a godaddy user and I am still having this problem... ...what do I need to do to remedy this?

**Comment by dwcandy** [comment]
Has there been any resolution to this issue yet? I am still unable to scroll on the sidebar menu.

**Comment by carlosua-memger** [comment]
I still having issues in this, does anyone resolved it?

**Comment by JawzoD3TH** [comment]
Nope

**Comment by rolandverhaar** [comment]
Is there any resolve yet?
Would really like to see this bug resolved.

**Comment by baconbutty20** [comment]
I could do with having this resolved. On tablet mode in landscape I can't scroll the sidebar???

**Comment by mountbatt** [comment]
https://github.com/godaddy-wordpress/primer-child-escapade/pull/39

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
