### ISSUE TITLE
How to change head image size

### ISSUE THREAD

**Issue by myDai98** [godaddy-wordpress/primer-child-escapade#70]
Hello,

The header image size is too big for me, how could I set up its width and height, or even hide it? Thanks!

<img width="724" alt="screen shot 2019-02-02 at 6 17 52 pm" src="https://user-images.githubusercontent.com/22860342/52170382-0ef24400-2717-11e9-943a-014977e6a43b.png">

**Comment by tatizz** [comment]
Did you find a solution? I have almost the same issue - I want my image bigger/none.

**Comment by baconbutty20** [comment]
Use Doncullen's code and just change the number of px.

.hero {
    height: 70px;
}

**Comment by bobby-webdev** [comment]
I do have the same problem with my website for a friend.
The size of the Image in Hero is not changeble..

Any idea how i can change the image size in the hero??

Thank you!

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
