### ISSUE TITLE
How to remove Hero Text from Header

### ISSUE THREAD

**Issue by GovPerm** [godaddy-wordpress/primer-child-escapade#72]
Hello,

I was wondering if there is a way to remove the Hero text (and background filler as well) from the header? The slider in the customizer won't let it go all the way to transparent, and there isn't an option to remove it.

Thanks,
gov

**Comment by doncullen** [comment]
I'm not the one who maintains this theme.  But thought I'd see if I could help ya.  Customize theme, additional CSS, pop in this:

```
#masthead {
display: none;
}
```

That'll remove the header section.  Alternatively, to just remove the text, do:

```
.hero .page-title-container {
display: none;
}
```

**Comment by GovPerm** [comment]
that second one worked perfectly for what I wanted to do. Thank you for the help.

Any idea how to get the sidebar to scroll with the body of the theme?

**Comment by doncullen** [comment]
Right now, it's locked via 

.side-masthead { position: fixed; }

.  I took a quick look at it and disabling that pretty much breaks the whole sidebar.  So the solution for that isn't as straightforward as I had hoped.  Sorry I wasn't of more help.

**Comment by Splinter1234** [comment]
> I'm not the one who maintains this theme. But thought I'd see if I could help ya. Customize theme, additional CSS, pop in this:
> 
> ```
> #masthead {
> display: none;
> }
> ```
> 
> That'll remove the header section. Alternatively, to just remove the text, do:
> 
> ```
> .hero .page-title-container {
> display: none;
> }
> ```

Thanks for your help, don
I used the code for removing menu text from the header image, but at the same time it shrinks the height of the header image.
Any way to fix that?
Cheers

**Comment by doncullen** [comment]
Could add this::

```
.hero {
    height: 240px;
}
```

Change height to whatever you prefer.  I haven't tested this (especially since I no longer use this theme), but in theory it should work.  If it doesn't provide link to your site that you're using this on and I'll take a look.

**Comment by Splinter1234** [comment]
Thank you very much, Don. That did the trick!

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
