### ISSUE TITLE
How to make sidebar menu slide up and down?

### ISSUE THREAD

**Issue by GovPerm** [godaddy-wordpress/primer-child-escapade#73]
not sure how to get the side menu slide up and down to show all the menu options.

**Comment by dmmoelle** [comment]
I am also having the same issue. I like the theme, but my menu items run off the bottom of the window. I have scaled the window to emphasize the issue. https://photos.app.goo.gl/L8pzmSjGdMMXi7PS7

**Comment by rvanlierop** [comment]
How can I increase the width of the side menu

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
