### ISSUE TITLE
Header image scales too large with a dark filter

### ISSUE THREAD

**Issue by Splinter1234** [godaddy-wordpress/primer-child-escapade#77]
No matter what size image I use for the header, it always scales up to an enormous size.
I suspect this has something to do with the header expecting a media file, maybe.
Added to which, there's a dark filter on the header which makes my bright white logo look grey.
Is there some custom CSS I can use to resolve both of these issues please?
Many thanks.

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
