### ISSUE TITLE
Hero Text repeated above Navigation menu?

### ISSUE THREAD

**Issue by Geeshgirl** [godaddy-wordpress/primer-child-escapade#80]
Looks like the last update added some unwanted flair.  All Text is repeated above Navigation Menu on right.  I have changed color of text to match background for now, but menu still appears lower than I want it.

Also, mobile version repeats Hero entirely with navigation bar background color.

Is anyone aware if this is a bug from latest update?  Last week everything looked fine.

Thanks,

Geeshgirl

**Comment by Geeshgirl** [comment]
I think it's a bug.  I've temporarily abandoned the theme for Primer.

**Comment by EvanHerman** [comment]
Hi @Geeshgirl 

What version of Escapade and Primer were/are you running? Is it the latest of both?

**Comment by Geeshgirl** [comment]
As far as I know, it would be the latest versions.

**Comment by Geeshgirl** [comment]
i.e., I wasn't offered an update.

**Comment by Geeshgirl** [comment]
Note: Primer looks fine.

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
