### ISSUE TITLE
How do I configure the theme to look like the screenshot? 

### ISSUE THREAD

**Issue by pantsmasterson** [godaddy-wordpress/primer-child-escapade#81]
In the screenshot for the theme, there's a very large (the full 2400x1300) image with text that begins with the header "Switzerland" and some lorem ipsum filler text. 

How do you set that up in the theme itself? "Header image" creates a very short image with a dark layer on top of it, but no text at all. There doesn't seem to be anywhere to enter the header, description, and button that you can see in the screenshot for the theme.

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
