### ISSUE TITLE
Different Fonts on Site Identity

### ISSUE THREAD

**Issue by diligent19** [godaddy-wordpress/primer-child-escapade#82]
I have set the Site Identity > Site Title to a specific phrase and it display as expected on the HOME page, but on every other page it displays differently and wraps, chopping off letters. Site is https://F1HomeServices.com 
![home01](https://user-images.githubusercontent.com/54598316/63799051-1ef29080-c8c0-11e9-8f30-3e901f5f343a.png)
![home02](https://user-images.githubusercontent.com/54598316/63799053-1ef29080-c8c0-11e9-82db-afea334c3d22.png)

and I have dug for days trying to find a solution. Any ideas?

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
