### ISSUE TITLE
Responsive mobile hamburger nav button not working

### ISSUE THREAD

**Issue by soundbytz** [godaddy-wordpress/primer-child-escapade#83]
I'm having an issue with the hamburger nav button in the responsive mobile viewport. Clicking on it doesn't produce a menu. I've tried various viewport sizes in Firefox's (desktop) responsive emulator and no size works until the viewport allows the full desktop nav. This is also happening on an Android smartphone using Firefox, Chrome, and Samsung Internet.

I have added CSS to the theme:

.site-header {height: 650px;}
.site-title {font-size: smaller;}
/*.hero-inner {visibility: hidden;}*/
.hero .page-title-container {
display: none;
}
table th, table td {border: 0px none #fff;}

I replaced .hero-inner {visibility: hidden;} with .hero .page-title-container {display: none;} based on a suggestion in another issue. I welcome any ideas for a solution. Thank you in advance.

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
