### ISSUE TITLE
Text color in the editor - Dark Color Scheme

### ISSUE THREAD

**Issue by ProfNemo** [godaddy-wordpress/primer-child-escapade#84]
I'm using the Dark color scheme with this theme (with the slight change of the link color from green to orange). It looks great, but in the WYSIWYG editor for writing my posts, the text is nearly unreadable. The light grey text against the white background doesn't work. When viewed against the dark background when on the actual site, the light grey is fine. 

So, how can I change the color of the text or the background in the WYSIWYG editor? 

Thanks for the help.
![Screen Shot 2019-10-10 at 8 14 05 PM](https://user-images.githubusercontent.com/56418700/66617480-ee7a6380-eb9a-11e9-98f5-8422eca4d1e9.png)

**Comment by RelativeParadox** [comment]
I also have the same problem, it seems the editor's color scheme is only responsive for the text and not the background color. I tried changing the editor-style.css colors manually but it did not work. I am using the blocks editor as well.

**Comment by AtilaCeki** [comment]
My solution was to install the [Dark mode](https://wordpress.org/plugins/dark-mode/) plugin. It's not perfect, namely headings look slightly different in the editor, but it's miles ahead of editing white text on white background :)

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
