### ISSUE TITLE
Change color of tagline (Escapade in WP)

### ISSUE THREAD

**Issue by cmyles33** [godaddy-wordpress/primer-child-escapade#85]
I'm trying to change the color of the tagline with no success. I go to Appearance>Customize>Colors>Content and go down to the tagline_text_color option put in the color code # and nothing happens. Is this a bug or am I doing something wrong? I don't have any problems changing other font colors, such as the header title. I've researched this topic, but haven't seen this issue or a solution, which leads me to believe it may be user error. ;-) Thanks for your assistance.

**Comment by AtilaCeki** [comment]
Yeah, it seems that _tagline_text_color_ doesn't do anything. Quick fix is to add the following to Additional CSS section:

`.site-description { color: #cccccc; }`

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
